"""Orchestrate derived player-packet and relationship-map artifacts."""

from __future__ import annotations

import argparse
import csv
import io
import itertools
import json
import sys
from collections import Counter
from pathlib import Path

from .paths import (
    CHARACTER_CONFIG_PATH,
    CHARACTER_INDEX_PATH,
    CLUE_INDEX_PATH,
    MYSTERIES_PATH,
    RELATIONSHIP_MAP_PATH,
    SPACE_INDEX_PATH,
)
from .rendering import (
    character_collection_tex,
    generated_readme,
    packet_tex,
    render_dot,
    render_mystery_mermaid,
    render_mystery_svg,
    render_mystery_tikz,
    render_svg,
    render_tikz,
)
from .source import (
    CHARACTER_RE,
    GENERATED_BY,
    SourceError,
    find_relationship_items,
    latex_to_plain,
    mysteries_in_dependency_order,
    owned_write,
    parse_configured_names,
    parse_mystery_dependencies,
    parse_sheets,
)


def build(root: Path, output: Path) -> dict[str, object]:
    """Generate every derived asset needed by the main document and players."""

    root = root.resolve()
    output = output.resolve()
    characters = parse_sheets(root, CHARACTER_INDEX_PATH, "CharacterSheet")
    spaces = parse_sheets(root, SPACE_INDEX_PATH, "SpaceSheet")
    clues = parse_sheets(root, CLUE_INDEX_PATH, "ClueSheet")
    mysteries = parse_sheets(root, MYSTERIES_PATH, "MysterySheet", argument_count=2)
    mystery_dependencies = parse_mystery_dependencies(root / MYSTERIES_PATH, mysteries)
    ordered_mysteries = mysteries_in_dependency_order(mysteries, mystery_dependencies)
    configured_names = parse_configured_names(root / CHARACTER_CONFIG_PATH)
    character_collection = character_collection_tex(root, characters)

    character_ids = {character.entity_id for character in characters}
    display_names = {
        character.entity_id: configured_names.get(character.entity_id, character.title)
        for character in characters
    }
    relationship_items = find_relationship_items(root / RELATIONSHIP_MAP_PATH)
    reference_counts: Counter[str] = Counter({identifier: 0 for identifier in character_ids})
    pair_counts: Counter[tuple[str, str]] = Counter()
    relationship_phrases: list[dict[str, object]] = []
    unknown_references: Counter[str] = Counter()

    for number, phrase in enumerate(relationship_items, start=1):
        references = [identifier.strip() for identifier in CHARACTER_RE.findall(phrase)]
        for identifier in references:
            if identifier in character_ids:
                reference_counts[identifier] += 1
            else:
                unknown_references[identifier] += 1
        participants = sorted(set(identifier for identifier in references if identifier in character_ids))
        for pair in itertools.combinations(participants, 2):
            pair_counts[pair] += 1
        relationship_phrases.append(
            {
                "number": number,
                "latex": phrase,
                "character_references": references,
                "known_characters": participants,
            }
        )

    configured_not_in_sheets = sorted(set(configured_names) - character_ids)
    no_configured_name = sorted(character_ids - set(configured_names))
    output.mkdir(parents=True, exist_ok=True)

    csv_buffer = io.StringIO(newline="")
    csv_buffer.write("# Generated by tools/generate_player_packets.py; do not edit.\n")
    writer = csv.DictWriter(csv_buffer, fieldnames=["character_id", "player_name", "role", "relationship_map_references"])
    writer.writeheader()
    for character in characters:
        writer.writerow(
            {
                "character_id": character.entity_id,
                "player_name": latex_to_plain(display_names[character.entity_id]),
                "role": latex_to_plain(character.title),
                "relationship_map_references": reference_counts[character.entity_id],
            }
        )
    owned_write(output / "relationship_counts.csv", csv_buffer.getvalue())

    analysis: dict[str, object] = {
        "generated_by": GENERATED_BY,
        "source_files": {
            "relationship_map": RELATIONSHIP_MAP_PATH.as_posix(),
            "character_index": CHARACTER_INDEX_PATH.as_posix(),
            "character_config": CHARACTER_CONFIG_PATH.as_posix(),
            "mysteries": MYSTERIES_PATH.as_posix(),
        },
        "character_reference_counts": [
            {
                "character_id": character.entity_id,
                "player_name": latex_to_plain(display_names[character.entity_id]),
                "role": latex_to_plain(character.title),
                "references": reference_counts[character.entity_id],
            }
            for character in characters
        ],
        "pair_reference_counts": [
            {"characters": list(pair), "shared_relationship_map_entries": weight}
            for pair, weight in sorted(pair_counts.items())
        ],
        "relationship_map_entries": relationship_phrases,
        "mystery_dependencies": [
            {"solve_first": before, "solve_next": after}
            for before, after in mystery_dependencies
        ],
        "validation": {
            "unknown_character_references_in_relationship_map": dict(sorted(unknown_references.items())),
            "configured_character_ids_without_sheets": configured_not_in_sheets,
            "characters_without_configured_player_name": no_configured_name,
        },
    }
    owned_write(output / "relationship_analysis.json", json.dumps(analysis, ensure_ascii=False, indent=2) + "\n")
    owned_write(output / "relationship_graph.dot", render_dot(display_names, pair_counts))
    owned_write(output / "relationship_graph.svg", render_svg(characters, display_names, pair_counts))
    owned_write(output / "relationship_graph.tex", render_tikz(characters, display_names, pair_counts))
    owned_write(output / "mystery_order.mmd", render_mystery_mermaid(ordered_mysteries, mystery_dependencies))
    owned_write(output / "mystery_order_graph.svg", render_mystery_svg(ordered_mysteries, mystery_dependencies))
    owned_write(output / "mystery_order_graph.tex", render_mystery_tikz(ordered_mysteries, mystery_dependencies))
    owned_write(output / "character_collection.tex", character_collection)
    owned_write(output / "README.md", generated_readme())

    for character in characters:
        owned_write(
            output / "players" / character.entity_id / "player_packet.tex",
            packet_tex(root, character, characters, spaces, clues, mysteries, character_collection),
        )

    return analysis


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="repository root (defaults to the directory above tools/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("generated"),
        help="output directory, relative to --root unless absolute (default: generated)",
    )
    return parser.parse_args()


def main() -> int:
    arguments = parse_args()
    root = arguments.root.resolve()
    output = arguments.output if arguments.output.is_absolute() else root / arguments.output
    try:
        analysis = build(root, output)
    except SourceError as error:
        print(f"Generation failed: {error}", file=sys.stderr)
        return 1

    characters = analysis["character_reference_counts"]
    pairs = analysis["pair_reference_counts"]
    print(f"Generated analysis and {len(characters)} player packets in {output.resolve()}")
    print(f"Analysed {len(analysis['relationship_map_entries'])} Relationship map entries and {len(pairs)} character pairs.")
    return 0
