"""Read, validate, and write the sources used by player-packet generation."""

from __future__ import annotations

import json
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping


GENERATED_BY = "tools/generate_player_packets.py"
PLAYER_PACKET_TEMPLATE = Path("layout/player_packet.template.tex")
PLAYER_PACKET_ENTITY_TEMPLATE = Path("layout/player_packet_entity.template.tex")
TEMPLATE_TOKEN_RE = re.compile(r"@@([A-Z][A-Z0-9_]*)@@")
GENERATED_MARKERS = (
    "% Generated by tools/generate_player_packets.py",
    "# Generated by tools/generate_player_packets.py",
    "// Generated by tools/generate_player_packets.py",
    "<!-- Generated by tools/generate_player_packets.py",
)
INPUT_RE = re.compile(r"\\input\s*\{([^{}]+)\}")
CHARACTER_RE = re.compile(r"\\Character\s*\{([^{}]+)\}")
CONFIGURED_NAME_RE = re.compile(r"\\MMCharacterName\s*\{([^{}]+)\}\s*\{([^{}]+)\}")
CHARACTER_IMAGE_SUFFIXES = (".png", ".jpg", ".jpeg", ".pdf")


@dataclass(frozen=True)
class Sheet:
    """An entity declaration discovered in one of the component indexes."""

    entity_id: str
    title: str
    source: Path
    latex: str


class SourceError(RuntimeError):
    """Raised when the repository's declared source structure is invalid."""


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError as error:
        raise SourceError(f"Required source file does not exist: {path}") from error


def render_template(path: Path, values: Mapping[str, str]) -> str:
    """Render a repository template containing ``@@UPPERCASE_TOKENS@@``."""

    template = read_text(path)
    tokens = {match.group(1) for match in TEMPLATE_TOKEN_RE.finditer(template)}
    missing = tokens - values.keys()
    unused = values.keys() - tokens
    if missing:
        raise SourceError(f"Template {path} is missing values for: {', '.join(sorted(missing))}")
    if unused:
        raise SourceError(f"Template {path} does not contain values for: {', '.join(sorted(unused))}")
    return TEMPLATE_TOKEN_RE.sub(lambda match: values[match.group(1)], template)


def tex_path(path: Path) -> str:
    """Return a path that is readable by TeX on every supported platform."""

    return path.as_posix()


def consume_braced(text: str, start: int) -> tuple[str, int]:
    """Read one balanced LaTeX braced argument starting at ``start``."""

    if start >= len(text) or text[start] != "{":
        raise SourceError(f"Expected '{{' near character {start}")
    depth = 0
    position = start
    while position < len(text):
        char = text[position]
        escaped = position > 0 and text[position - 1] == "\\"
        if char == "{" and not escaped:
            depth += 1
        elif char == "}" and not escaped:
            depth -= 1
            if depth == 0:
                return text[start + 1 : position], position + 1
        position += 1
    raise SourceError(f"Unclosed '{{' near character {start}")


def extract_macro_calls(text: str, macro: str, argument_count: int = 3) -> list[tuple[list[str], str]]:
    """Extract full calls and their balanced arguments for a simple LaTeX macro."""

    token = f"\\{macro}"
    results: list[tuple[list[str], str]] = []
    search_from = 0
    while True:
        start = text.find(token, search_from)
        if start == -1:
            break
        token_end = start + len(token)
        if token_end < len(text) and text[token_end].isalpha():
            search_from = token_end
            continue
        position = token_end
        arguments: list[str] = []
        try:
            for _ in range(argument_count):
                while position < len(text) and text[position].isspace():
                    position += 1
                argument, position = consume_braced(text, position)
                arguments.append(argument)
        except SourceError:
            search_from = token_end
            continue
        results.append((arguments, text[start:position]))
        search_from = position
    return results


def resolve_input(root: Path, including_file: Path, target: str) -> Path:
    relative_target = Path(target)
    if relative_target.suffix == "":
        relative_target = relative_target.with_suffix(".tex")
    candidate = (root / relative_target).resolve()
    if not candidate.is_file():
        candidate = (including_file.parent / relative_target).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as error:
        raise SourceError(f"Input outside the repository is not supported: {target}") from error
    if not candidate.is_file():
        raise SourceError(f"Could not resolve \\input{{{target}}} from {including_file}")
    return candidate


def files_from_index(root: Path, index_file: Path) -> list[Path]:
    """Return an index and the local files it transitively includes, in order."""

    seen: set[Path] = set()
    files: list[Path] = []

    def visit(path: Path) -> None:
        path = path.resolve()
        if path in seen:
            return
        seen.add(path)
        files.append(path)
        for target in INPUT_RE.findall(read_text(path)):
            visit(resolve_input(root, path, target))

    visit(index_file.resolve())
    return files


def parse_sheets(root: Path, index_relative_path: str, macro: str, argument_count: int = 3) -> list[Sheet]:
    """Parse entity sheets whose first argument is an identifier.

    Mysteries are intentionally different: their two-argument form uses the
    first argument as both the visible label and the reference key.
    """

    sheets: list[Sheet] = []
    for source in files_from_index(root, root / index_relative_path):
        for arguments, latex in extract_macro_calls(read_text(source), macro, argument_count):
            title = arguments[0].strip() if argument_count == 2 else arguments[1].strip()
            sheets.append(Sheet(arguments[0].strip(), title, source, latex.strip()))
    duplicate_ids = [entity_id for entity_id, count in Counter(sheet.entity_id for sheet in sheets).items() if count > 1]
    if duplicate_ids:
        raise SourceError(f"Duplicate {macro} identifiers: {', '.join(sorted(duplicate_ids))}")
    return sheets


def parse_configured_names(root: Path) -> dict[str, str]:
    return {
        identifier.strip(): name.strip()
        for identifier, name in CONFIGURED_NAME_RE.findall(read_text(root / "config/characters.tex"))
    }


def character_short_description(character: Sheet) -> str:
    """Return a character's optional ``\\shortdescription`` body."""

    descriptions = extract_macro_calls(character.latex, "shortdescription", argument_count=1)
    if len(descriptions) > 1:
        raise SourceError(f"Character '{character.entity_id}' declares more than one \\shortdescription")
    return descriptions[0][0][0].strip() if descriptions else ""


def character_image_path(root: Path, character_id: str) -> str:
    """Return a TeX-readable character image path, falling back to the placeholder."""

    image_directory = root / "config/character_imgs"
    matches = sorted(
        candidate
        for candidate in image_directory.glob(f"{character_id}.*")
        if candidate.is_file() and candidate.stem == character_id and candidate.suffix.lower() in CHARACTER_IMAGE_SUFFIXES
    )
    image = matches[0] if matches else image_directory / "placeholder.png"
    if not image.is_file():
        raise SourceError(
            f"No image exists for character '{character_id}' and the placeholder is missing: {image_directory / 'placeholder.png'}"
        )
    return tex_path(image.relative_to(root))


def parse_mystery_dependencies(root: Path, mysteries: list[Sheet]) -> list[tuple[str, str]]:
    """Read ``\\MysteryDependency{solve-first}{solve-next}`` declarations."""

    dependencies = [
        (arguments[0].strip(), arguments[1].strip())
        for arguments, _ in extract_macro_calls(read_text(root / "content/mysteries.tex"), "MysteryDependency", 2)
    ]
    known_labels = {mystery.entity_id for mystery in mysteries}
    unknown_labels = sorted({label for dependency in dependencies for label in dependency if label not in known_labels})
    if unknown_labels:
        raise SourceError("Mystery dependencies refer to undeclared labels: " + ", ".join(unknown_labels))
    return dependencies


def mysteries_in_dependency_order(mysteries: list[Sheet], dependencies: list[tuple[str, str]]) -> list[Sheet]:
    """Return a stable topological order, preserving source order where possible."""

    source_order = [mystery.entity_id for mystery in mysteries]
    successors: dict[str, set[str]] = {label: set() for label in source_order}
    incoming: dict[str, int] = {label: 0 for label in source_order}
    for before, after in dependencies:
        if after not in successors[before]:
            successors[before].add(after)
            incoming[after] += 1

    ordered_labels: list[str] = []
    ready = [label for label in source_order if incoming[label] == 0]
    while ready:
        label = ready.pop(0)
        ordered_labels.append(label)
        for successor in source_order:
            if successor in successors[label]:
                incoming[successor] -= 1
                if incoming[successor] == 0:
                    ready.append(successor)

    if len(ordered_labels) != len(source_order):
        raise SourceError("Mystery dependencies contain a cycle")
    by_label = {mystery.entity_id: mystery for mystery in mysteries}
    return [by_label[label] for label in ordered_labels]


def find_relationship_items(root: Path) -> list[str]:
    source = read_text(root / "content/relations-and-notes.tex")
    heading = re.search(r"\\subsection\s*\{Relationship map\}", source)
    if not heading:
        raise SourceError("content/relations-and-notes.tex has no 'Relationship map' subsection")
    following_subsection = re.search(r"\\subsection\s*\{", source[heading.end() :])
    section = source[heading.end() : heading.end() + following_subsection.start()] if following_subsection else source[heading.end() :]
    match = re.search(r"\\begin\s*\{itemize\}(.*?)\\end\s*\{itemize\}", section, flags=re.DOTALL)
    if not match:
        raise SourceError("The Relationship map subsection must contain an itemize environment")
    items = re.split(r"\\item(?:\s*\[[^\]]*\])?", match.group(1))
    return [re.sub(r"\s+", " ", item).strip() for item in items[1:] if item.strip()]


def latex_to_plain(text: str) -> str:
    """Provide a readable graph label without attempting full TeX rendering."""

    previous = None
    result = text
    while previous != result:
        previous = result
        result = re.sub(r"\\[A-Za-z@]+\s*\{([^{}]*)\}", r"\1", result)
    result = re.sub(r"\\[A-Za-z@]+", "", result)
    result = result.replace("{", "").replace("}", "")
    return re.sub(r"\s+", " ", result).strip()


def owned_write(path: Path, content: str) -> None:
    """Write one generated file without replacing a non-generated user file."""

    if path.exists():
        existing = read_text(path)
        if existing == content:
            return
        is_owned_json = False
        if path.suffix == ".json":
            try:
                is_owned_json = json.loads(existing).get("generated_by") == GENERATED_BY
            except json.JSONDecodeError:
                pass
        if not existing.startswith(GENERATED_MARKERS) and not is_owned_json:
            raise SourceError(f"Refusing to replace non-generated file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def player_safe_rules(root: Path) -> str:
    """Copy the dedicated player rules while keeping authoring guidance GM-only."""

    source = read_text(root / "content/general_rules.tex")
    gm_rules = read_text(root / "content/gm_rules.tex")
    host_guidance = re.compile(r"^\\subsection\s*\{How to create a game\}", flags=re.MULTILINE)

    if host_guidance.search(source):
        raise SourceError(
            "Host guidance belongs in content/gm_rules.tex, not content/general_rules.tex"
        )
    if not host_guidance.search(gm_rules):
        raise SourceError("content/gm_rules.tex must mark host guidance with 'How to create a game'")
    return source.rstrip()
