#!/usr/bin/env python3
"""Generate player-safe LaTeX packets and relationship-map analysis.

The source of truth remains the files in ``content/`` and ``config/``.  This
tool deliberately copies only the public rules and one character sheet into
each packet; GM-only material is never included.
"""

from __future__ import annotations

import argparse
import csv
import html
import io
import itertools
import json
import math
import os
import re
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


GENERATED_BY = "tools/generate_player_packets.py"
GENERATED_MARKERS = (
    "% Generated by tools/generate_player_packets.py",
    "# Generated by tools/generate_player_packets.py",
    "// Generated by tools/generate_player_packets.py",
    "<!-- Generated by tools/generate_player_packets.py",
)
INPUT_RE = re.compile(r"\\input\s*\{([^{}]+)\}")
CHARACTER_RE = re.compile(r"\\Character\s*\{([^{}]+)\}")
CONFIGURED_NAME_RE = re.compile(r"\\MMCharacterName\s*\{([^{}]+)\}\s*\{([^{}]+)\}")


@dataclass(frozen=True)
class Sheet:
    """An entity declaration discovered in one of the component indexes."""

    entity_id: str
    title: str
    source: Path
    latex: str


class SourceError(RuntimeError):
    """Raised when the repository's declared source structure is invalid."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root (defaults to the directory above tools/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("generated"),
        help="output directory, relative to --root unless absolute (default: generated)",
    )
    return parser.parse_args()


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError as error:
        raise SourceError(f"Required source file does not exist: {path}") from error


def tex_path(path: Path) -> str:
    """Return a path that is readable by TeX on every supported platform."""

    return path.as_posix()


def consume_braced(text: str, start: int) -> tuple[str, int]:
    """Read one balanced LaTeX braced argument starting at ``start``."""

    if start >= len(text) or text[start] != "{":
        raise SourceError(f"Expected '{{' near character {start}")
    depth = 0
    position = start
    while position < len(text):
        char = text[position]
        escaped = position > 0 and text[position - 1] == "\\"
        if char == "{" and not escaped:
            depth += 1
        elif char == "}" and not escaped:
            depth -= 1
            if depth == 0:
                return text[start + 1 : position], position + 1
        position += 1
    raise SourceError(f"Unclosed '{{' near character {start}")


def extract_macro_calls(text: str, macro: str, argument_count: int = 3) -> list[tuple[list[str], str]]:
    """Extract full calls and their balanced arguments for a simple LaTeX macro."""

    token = f"\\{macro}"
    results: list[tuple[list[str], str]] = []
    search_from = 0
    while True:
        start = text.find(token, search_from)
        if start == -1:
            break
        token_end = start + len(token)
        if token_end < len(text) and text[token_end].isalpha():
            search_from = token_end
            continue
        position = token_end
        arguments: list[str] = []
        try:
            for _ in range(argument_count):
                while position < len(text) and text[position].isspace():
                    position += 1
                argument, position = consume_braced(text, position)
                arguments.append(argument)
        except SourceError:
            search_from = token_end
            continue
        results.append((arguments, text[start:position]))
        search_from = position
    return results


def resolve_input(root: Path, including_file: Path, target: str) -> Path:
    relative_target = Path(target)
    if relative_target.suffix == "":
        relative_target = relative_target.with_suffix(".tex")
    candidate = (root / relative_target).resolve()
    if not candidate.is_file():
        candidate = (including_file.parent / relative_target).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as error:
        raise SourceError(f"Input outside the repository is not supported: {target}") from error
    if not candidate.is_file():
        raise SourceError(f"Could not resolve \\input{{{target}}} from {including_file}")
    return candidate


def files_from_index(root: Path, index_file: Path) -> list[Path]:
    """Return an index and the local files it transitively includes, in order."""

    seen: set[Path] = set()
    files: list[Path] = []

    def visit(path: Path) -> None:
        path = path.resolve()
        if path in seen:
            return
        seen.add(path)
        files.append(path)
        for target in INPUT_RE.findall(read_text(path)):
            visit(resolve_input(root, path, target))

    visit(index_file.resolve())
    return files


def parse_sheets(root: Path, index_relative_path: str, macro: str) -> list[Sheet]:
    sheets: list[Sheet] = []
    for source in files_from_index(root, root / index_relative_path):
        for arguments, latex in extract_macro_calls(read_text(source), macro):
            sheets.append(Sheet(arguments[0].strip(), arguments[1].strip(), source, latex.strip()))
    duplicate_ids = [entity_id for entity_id, count in Counter(sheet.entity_id for sheet in sheets).items() if count > 1]
    if duplicate_ids:
        raise SourceError(f"Duplicate {macro} identifiers: {', '.join(sorted(duplicate_ids))}")
    return sheets


def parse_configured_names(root: Path) -> dict[str, str]:
    return {identifier.strip(): name.strip() for identifier, name in CONFIGURED_NAME_RE.findall(read_text(root / "config/characters.tex"))}


def find_relationship_items(root: Path) -> list[str]:
    source = read_text(root / "content/relations-and-notes.tex")
    heading = re.search(r"\\subsection\s*\{Relationship map\}", source)
    if not heading:
        raise SourceError("content/relations-and-notes.tex has no 'Relationship map' subsection")
    following_subsection = re.search(r"\\subsection\s*\{", source[heading.end() :])
    section = source[heading.end() : heading.end() + following_subsection.start()] if following_subsection else source[heading.end() :]
    match = re.search(r"\\begin\s*\{itemize\}(.*?)\\end\s*\{itemize\}", section, flags=re.DOTALL)
    if not match:
        raise SourceError("The Relationship map subsection must contain an itemize environment")
    items = re.split(r"\\item(?:\s*\[[^\]]*\])?", match.group(1))
    return [re.sub(r"\s+", " ", item).strip() for item in items[1:] if item.strip()]


def latex_to_plain(text: str) -> str:
    """Provide a readable graph label without attempting full TeX rendering."""

    previous = None
    result = text
    while previous != result:
        previous = result
        result = re.sub(r"\\[A-Za-z@]+\s*\{([^{}]*)\}", r"\1", result)
    result = re.sub(r"\\[A-Za-z@]+", "", result)
    result = result.replace("{", "").replace("}", "")
    return re.sub(r"\s+", " ", result).strip()


def owned_write(path: Path, content: str) -> None:
    """Write one generated file without replacing a non-generated user file."""

    if path.exists():
        existing = read_text(path)
        if existing == content:
            return
        is_owned_json = False
        if path.suffix == ".json":
            try:
                is_owned_json = json.loads(existing).get("generated_by") == GENERATED_BY
            except json.JSONDecodeError:
                pass
        if not existing.startswith(GENERATED_MARKERS) and not is_owned_json:
            raise SourceError(f"Refusing to replace non-generated file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def generated_readme() -> str:
    return """<!-- Generated by tools/generate_player_packets.py; do not edit this directory. -->
# Generated murder mystery materials

Run `python tools/generate_player_packets.py` from the repository root after editing the game sources.

- `relationship_counts.csv` and `relationship_analysis.json` list character references in the Relationship map.
- `relationship_graph.svg` is the rendered network; `relationship_graph.tex` is its PDFLaTeX-native companion. Edge width and opacity grow with the number of Relationship map entries shared by a pair.
- `players/<character-id>/player_packet.tex` is a self-contained, player-safe LaTeX document containing the public rules and only that character's sheet.

The packets intentionally omit the relationship map, clues, mysteries, full background, and other character sheets. Edit `content/` and `config/`, never these generated files.
"""


def player_safe_rules(root: Path) -> str:
    """Copy the player rules while leaving authoring guidance with the GM."""

    source = read_text(root / "content/general_rules.tex")
    host_guidance = re.search(r"^\\subsection\s*\{How to create a game\}", source, flags=re.MULTILINE)
    if not host_guidance:
        raise SourceError("content/general_rules.tex must mark host guidance with 'How to create a game'")
    return source[: host_guidance.start()].rstrip()


def render_svg(
    characters: list[Sheet],
    display_names: dict[str, str],
    pair_counts: Counter[tuple[str, str]],
) -> str:
    width, height = 1200, 900
    center_x, center_y, radius = width / 2, height / 2, 310
    coordinates: dict[str, tuple[float, float]] = {}
    for index, character in enumerate(characters):
        angle = -math.pi / 2 + (2 * math.pi * index / max(len(characters), 1))
        coordinates[character.entity_id] = (center_x + radius * math.cos(angle), center_y + radius * math.sin(angle))

    max_weight = max(pair_counts.values(), default=1)
    edge_parts: list[str] = []
    for (first, second), weight in sorted(pair_counts.items()):
        x1, y1 = coordinates[first]
        x2, y2 = coordinates[second]
        strength = weight / max_weight
        opacity = 0.18 + 0.82 * strength
        stroke_width = 1.2 + 7.0 * strength
        edge_parts.append(
            f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
            f'stroke="#6E2034" stroke-width="{stroke_width:.2f}" stroke-opacity="{opacity:.2f}" />'
        )
        midpoint_x, midpoint_y = (x1 + x2) / 2, (y1 + y2) / 2
        edge_parts.append(
            f'<text x="{midpoint_x:.1f}" y="{midpoint_y - 5:.1f}" class="edge-label">{weight}</text>'
        )

    node_parts: list[str] = []
    for character in characters:
        x, y = coordinates[character.entity_id]
        name = html.escape(latex_to_plain(display_names[character.entity_id]))
        role = html.escape(latex_to_plain(character.title))
        node_parts.extend(
            [
                f'<circle cx="{x:.1f}" cy="{y:.1f}" r="55" class="node" />',
                f'<text x="{x:.1f}" y="{y - 3:.1f}" class="node-name">{name}</text>',
                f'<text x="{x:.1f}" y="{y + 19:.1f}" class="node-role">{role}</text>',
            ]
        )

    return f"""<!-- Generated by tools/generate_player_packets.py; do not edit. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title description">
  <title id="title">Relationship map character network</title>
  <desc id="description">Each line connects characters mentioned in the same Relationship map item. Darker, wider lines represent more shared items. The number on a line is the shared-item count.</desc>
  <style>
    .background {{ fill: #F4F1F2; }}
    .title {{ fill: #25202A; font: 700 30px serif; text-anchor: middle; }}
    .subtitle {{ fill: #4A4248; font: 16px sans-serif; text-anchor: middle; }}
    .node {{ fill: #FFFFFF; stroke: #6E2034; stroke-width: 2.5; }}
    .node-name {{ fill: #25202A; font: 700 15px sans-serif; text-anchor: middle; }}
    .node-role {{ fill: #4A4248; font: 12px sans-serif; text-anchor: middle; }}
    .edge-label {{ fill: #6E2034; font: 700 13px sans-serif; text-anchor: middle; paint-order: stroke; stroke: #F4F1F2; stroke-width: 5; stroke-linejoin: round; }}
  </style>
  <rect width="100%" height="100%" class="background" />
  <text x="{center_x}" y="48" class="title">Relationship map</text>
  <text x="{center_x}" y="76" class="subtitle">Lines strengthen and become less transparent as two characters share more entries.</text>
  <g aria-label="Connections">{''.join(edge_parts)}</g>
  <g aria-label="Characters">{''.join(node_parts)}</g>
</svg>
"""


def render_tikz(
    characters: list[Sheet],
    display_names: dict[str, str],
    pair_counts: Counter[tuple[str, str]],
) -> str:
    """Create a PDFLaTeX-native rendering of the same graph as the SVG."""

    width, height = 12.0, 9.0
    center_x, center_y, radius = width / 2, height / 2, 3.1
    coordinates: dict[str, tuple[float, float]] = {}
    node_names: dict[str, str] = {}
    for index, character in enumerate(characters):
        angle = -math.pi / 2 + (2 * math.pi * index / max(len(characters), 1))
        coordinates[character.entity_id] = (center_x + radius * math.cos(angle), center_y + radius * math.sin(angle))
        node_names[character.entity_id] = f"relationship-node-{index}"

    max_weight = max(pair_counts.values(), default=1)
    lines = [
        "% Generated by tools/generate_player_packets.py; do not edit.",
        "\\begin{center}",
        "\\begin{tikzpicture}[x=0.075\\linewidth,y=0.075\\linewidth]",
        "  \\path[use as bounding box] (0,0) rectangle (12,9);",
        "  \\tikzset{relationship node/.style={draw=wine, fill=white, ellipse, align=center, minimum width=1.55cm, minimum height=0.95cm, inner sep=2pt}}",
    ]
    for character in characters:
        x, y = coordinates[character.entity_id]
        name = display_names[character.entity_id]
        role = character.title
        lines.append(
            f"  \\node[relationship node] ({node_names[character.entity_id]}) at ({x:.3f},{y:.3f}) "
            f"{{\\shortstack{{{name}\\\\[-0.15em]\\scriptsize {role}}}}};"
        )
    for (first, second), weight in sorted(pair_counts.items()):
        strength = weight / max_weight
        opacity = 0.18 + 0.82 * strength
        line_width = 0.25 + 1.0 * strength
        lines.append(
            f"  \\draw[wine, opacity={opacity:.2f}, line width={line_width:.2f}pt] "
            f"({node_names[first]}) -- node[midway, fill=fog, inner sep=1pt, font=\\scriptsize\\bfseries] {{{weight}}} "
            f"({node_names[second]});"
        )
    lines.extend(["\\end{tikzpicture}", "\\end{center}", ""])
    return "\n".join(lines)


def render_dot(display_names: dict[str, str], pair_counts: Counter[tuple[str, str]]) -> str:
    max_weight = max(pair_counts.values(), default=1)
    lines = [
        "// Generated by tools/generate_player_packets.py; do not edit.",
        "graph RelationshipMap {",
        '  graph [bgcolor="#F4F1F2", overlap=false, splines=true];',
        '  node [shape=ellipse, style="filled", fillcolor="white", color="#6E2034", fontname="Helvetica"];',
        '  edge [color="#6E2034", fontname="Helvetica"];',
    ]
    for identifier, display_name in sorted(display_names.items()):
        lines.append(f'  "{identifier}" [label="{latex_to_plain(display_name).replace(chr(34), chr(39))}"];')
    for (first, second), weight in sorted(pair_counts.items()):
        penwidth = 1.2 + 7.0 * weight / max_weight
        lines.append(f'  "{first}" -- "{second}" [label="{weight}", penwidth="{penwidth:.2f}"];')
    lines.append("}")
    return "\n".join(lines) + "\n"


def packet_tex(
    root: Path,
    character: Sheet,
    characters: list[Sheet],
    spaces: list[Sheet],
    clues: list[Sheet],
    mysteries: list[Sheet],
) -> str:
    """Create a standalone snapshot with public rules and one sheet."""

    preamble = read_text(root / "layout/preamble.tex").strip()
    game_config = read_text(root / "config/game.tex").strip()
    configured_names = read_text(root / "config/characters.tex").strip()
    public_rules = player_safe_rules(root)

    declarations: list[str] = []
    for kind, sheets in (("character", characters), ("space", spaces), ("clue", clues), ("mystery", mysteries)):
        for sheet in sheets:
            declarations.append(f"\\MMRegisterEntity{{{kind}}}{{{sheet.entity_id}}}{{{sheet.title}}}")

    return rf"""% Generated by tools/generate_player_packets.py; do not edit.
% Source snapshot: {tex_path(character.source.relative_to(root))}
% Compile from the repository root, for example:
%   latexmk -pdf -outdir=target/players/{character.entity_id} generated/players/{character.entity_id}/player_packet.tex
\documentclass[a4paper,11pt]{{article}}

% Copied presentation and game configuration
{preamble}

\makeatletter
\newcommand{{\MMCharacterName}}[2]{{%
  \expandafter\gdef\csname mm@configured@character@#1\endcsname{{#2}}%
}}
\newcommand{{\MMRegisterEntity}}[3]{{%
  \def\MMEntityKind{{#1}}%
  \def\MMEntityId{{#2}}%
  \ifx\MMEntityKind\@empty\else
    \expandafter\gdef\csname mm@player@#1@#2\endcsname{{#3}}%
  \fi
}}
\newcommand{{\MMRegisteredName}}[2]{{%
  \@ifundefined{{mm@player@#1@#2}}{{\textbf{{[unknown #1: #2]}}}}{{\csname mm@player@#1@#2\endcsname}}%
}}
\newcommand{{\MMPlayerCharacterName}}[1]{{%
  \@ifundefined{{mm@configured@character@#1}}{{\MMRegisteredName{{character}}{{#1}}}}{{\csname mm@configured@character@#1\endcsname}}%
}}
\makeatother

{configured_names}

{game_config}

% Entity names are copied only to resolve references in this player's sheet.
{chr(10).join(declarations)}

\newcommand{{\CharacterName}}[1]{{\MMPlayerCharacterName{{#1}}}}
\newcommand{{\SpaceName}}[1]{{\MMRegisteredName{{space}}{{#1}}}}
\newcommand{{\ClueName}}[1]{{\MMRegisteredName{{clue}}{{#1}}}}
\newcommand{{\Character}}[1]{{\CharacterReferenceStyle{{\CharacterName{{#1}}}}}}
\newcommand{{\Space}}[1]{{\SpaceReferenceStyle{{\SpaceName{{#1}}}}}}
\newcommand{{\Clue}}[1]{{\ClueReferenceStyle{{\ClueName{{#1}}}}}}
\newcommand{{\Mystery}}[1]{{\MysteryReferenceStyle{{\MMRegisteredName{{mystery}}{{#1}}}}}}
\newcommand{{\timestamp}}[1]{{\TimestampStyle{{#1}}}}
\newcommand{{\outsideentity}}[1]{{\OutsideEntityStyle{{#1}}}}
\newcommand{{\CharacterSheet}}[3]{{%
  \subsection{{#2: \CharacterReferenceStyle{{\CharacterName{{#1}}}}}}%
  #3%
}}

\begin{{document}}
\pagenumbering{{arabic}}
\begin{{center}}
  {{\Huge\bfseries\color{{ink}}\GameTitle\par}}
  \vspace{{0.5em}}
  {{\Large\color{{wine}}Player packet for \CharacterName{{{character.entity_id}}}\par}}
\end{{center}}

% Copied public rules
{public_rules}

\clearpage
\section{{Your character}}

% Copied character sheet
{character.latex}

\end{{document}}
"""


def build(root: Path, output: Path) -> dict[str, object]:
    root = root.resolve()
    output = output.resolve()
    characters = parse_sheets(root, "content/characters/index.tex", "CharacterSheet")
    spaces = parse_sheets(root, "content/spaces/index.tex", "SpaceSheet")
    clues = parse_sheets(root, "content/clues/index.tex", "ClueSheet")
    mysteries = parse_sheets(root, "content/mysteries.tex", "MysterySheet")
    configured_names = parse_configured_names(root)

    character_ids = {character.entity_id for character in characters}
    display_names = {
        character.entity_id: configured_names.get(character.entity_id, character.title)
        for character in characters
    }
    relationship_items = find_relationship_items(root)
    reference_counts: Counter[str] = Counter({identifier: 0 for identifier in character_ids})
    pair_counts: Counter[tuple[str, str]] = Counter()
    relationship_phrases: list[dict[str, object]] = []
    unknown_references: Counter[str] = Counter()

    for number, phrase in enumerate(relationship_items, start=1):
        references = [identifier.strip() for identifier in CHARACTER_RE.findall(phrase)]
        for identifier in references:
            if identifier in character_ids:
                reference_counts[identifier] += 1
            else:
                unknown_references[identifier] += 1
        participants = sorted(set(identifier for identifier in references if identifier in character_ids))
        for pair in itertools.combinations(participants, 2):
            pair_counts[pair] += 1
        relationship_phrases.append(
            {
                "number": number,
                "latex": phrase,
                "character_references": references,
                "known_characters": participants,
            }
        )

    configured_not_in_sheets = sorted(set(configured_names) - character_ids)
    no_configured_name = sorted(character_ids - set(configured_names))
    output.mkdir(parents=True, exist_ok=True)

    csv_buffer = io.StringIO(newline="")
    csv_buffer.write("# Generated by tools/generate_player_packets.py; do not edit.\n")
    writer = csv.DictWriter(csv_buffer, fieldnames=["character_id", "player_name", "role", "relationship_map_references"])
    writer.writeheader()
    for character in characters:
        writer.writerow(
            {
                "character_id": character.entity_id,
                "player_name": latex_to_plain(display_names[character.entity_id]),
                "role": latex_to_plain(character.title),
                "relationship_map_references": reference_counts[character.entity_id],
            }
        )
    owned_write(output / "relationship_counts.csv", csv_buffer.getvalue())

    analysis: dict[str, object] = {
        "generated_by": GENERATED_BY,
        "source_files": {
            "relationship_map": "content/relations-and-notes.tex",
            "character_index": "content/characters/index.tex",
            "character_config": "config/characters.tex",
        },
        "character_reference_counts": [
            {
                "character_id": character.entity_id,
                "player_name": latex_to_plain(display_names[character.entity_id]),
                "role": latex_to_plain(character.title),
                "references": reference_counts[character.entity_id],
            }
            for character in characters
        ],
        "pair_reference_counts": [
            {"characters": list(pair), "shared_relationship_map_entries": weight}
            for pair, weight in sorted(pair_counts.items())
        ],
        "relationship_map_entries": relationship_phrases,
        "validation": {
            "unknown_character_references_in_relationship_map": dict(sorted(unknown_references.items())),
            "configured_character_ids_without_sheets": configured_not_in_sheets,
            "characters_without_configured_player_name": no_configured_name,
        },
    }
    owned_write(output / "relationship_analysis.json", json.dumps(analysis, ensure_ascii=False, indent=2) + "\n")
    owned_write(output / "relationship_graph.dot", render_dot(display_names, pair_counts))
    owned_write(output / "relationship_graph.svg", render_svg(characters, display_names, pair_counts))
    owned_write(output / "relationship_graph.tex", render_tikz(characters, display_names, pair_counts))
    owned_write(output / "README.md", generated_readme())

    for character in characters:
        owned_write(
            output / "players" / character.entity_id / "player_packet.tex",
            packet_tex(root, character, characters, spaces, clues, mysteries),
        )

    return analysis


def main() -> int:
    arguments = parse_args()
    root = arguments.root.resolve()
    output = arguments.output if arguments.output.is_absolute() else root / arguments.output
    try:
        analysis = build(root, output)
    except SourceError as error:
        print(f"Generation failed: {error}", file=sys.stderr)
        return 1

    characters = analysis["character_reference_counts"]
    pairs = analysis["pair_reference_counts"]
    print(f"Generated analysis and {len(characters)} player packets in {output.resolve()}")
    print(f"Analysed {len(analysis['relationship_map_entries'])} Relationship map entries and {len(pairs)} character pairs.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
